#!/bin/sh

logfile=/tmp/startdwm.log
exec > $logfile 2>&1

set -x

# relaunch DWM if the binary changes, otherwise bail
{
csum=""
new_csum=$(sha1sum $(which dwm))
while true
do
    if [ "$csum" != "$new_csum" ]
    then
        csum=$new_csum
        dwm
    else
        exit 0
    fi
    new_csum=$(sha1sum $(which dwm))
    echo "Calculating new checksum for $(which dwm): ${new_csum} (old: ${csum})"
    sleep 0.5
done
} > $logfile
